print("What is your name?")
name = input()
print("How old are you?")
years = input()
print("Where are you live?")
place = input()
print("Hello,", name)
print("Your age is", years)
print("You live in", place)